# Site settings
title: "Econometrics I"
description: "Simple regression model and OLS Estimate, Assumptions of Classical Linear Regression model, Interval estimate and hypothesis testing, Alternative Functional forms of regression models, Multivariate regression model and inference, Maximum likelihood method, structural stability tests, matrix approach to regression model"
baseurl: "/ecn301e"
url: "http://itueconomics.github.io"
twitter_username: ituecon
github_username:  itueconomics

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
